### ISSUE TITLE
Cant build with mvn

### ISSUE THREAD

**Issue by jamesxsc** [Avicus/AvicusNetwork#3]
Getting errors with any kind of maven command. Can someone either try and post a .jar here for atlas or try and fix the errors. Main error is .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml

**Comment by jamesxsc** [comment]
UPDATE : managed to run but cant resolve the dependencies, presumably because the avicus site is down, any ideas of a solution?

**Comment by thekeenant** [comment]
Please paste the entire log message into pastebin and link it here. It is likely because you haven't built a necessary dependency.

**Comment by jamesxsc** [comment]
Yes i realise this now.

**Comment by ghost** [comment]
there is 1 file that doesn't build
https://hastebin.com/jegusoqiha.sql
